import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import TopNavbar from "@/components/navbar/TopNavbar";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <Provider>
          <TopNavbar />
          <main className="container mx-auto">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
